eureka:
  client:
    serviceUrl:
      defaultZone: @eureka.client.serviceUrl.defaultZone@
  instance:
    prefer-ip-address: true

server:
  port: 8081
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-threads: 2000
    accept-count: 3000
    max-connections: 20000
    min-spare-threads: 50
  connection-timeout: 20000
#
#  datasource
#
skyler:
  env:
    app-name: skyler-dev
    name: dev
    version: 1.0
  common:
    item1: dfasfd
    item2: sss
  datasource:
    home:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: @skyler.datasource.home.url@
      username: @skyler.datasource.home.username@
      password: @skyler.datasource.home.password@
      max-active: 10
      min-idle: 0
    school:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: @skyler.datasource.school.url@
      username: @skyler.datasource.school.username@
      password: @skyler.datasource.school.password@
      max-active: 10
      min-idle: 0

#
# spring 
#
spring:
  application:
    name: springboot-mybatis-multi_source
  mvc:
    favicon:
      enabled: false
  messages:
      basename: messages/messages
      always-use-message-format: true
      cache-seconds: 3600
  aop:
    proxy-target-class: true
#  redis:
#    host: @spring.redis.host@
#    port: @spring.redis.port@
#    timeout: @spring.redis.timeout@
#    test-on-borrow: @spring.redis.testOnBorrow@
#    password: @spring.redis.password@
#    pool:
#      max-active: @spring.redis.pool.max-active@
#      max-idle: @spring.redis.pool.max-idle@
#      max-wait: @spring.redis.pool.max-wait@
#      min-idle: @spring.redis.pool.min-idle@
#
# actuator
#
management:
  security:
    enabled: false
  add-application-context-header: false

#
# my spring mvc
#
#my:
#  spring:
#    security:
#      csrf:
#        referer: @my.spring.security.csrf.referer@
#      jwt:
#        header: Authorization
#        secret: @my.spring.security.jwt.secret@
#        expiration: @my.spring.security.jwt.expiration@

#
# logging config file location
# logback.xml和logback-spring.xml选择任意一个，两个文件只是获取属性的方式不同
# logback-spring.xml用的是@@，而logback.xml用的是${}
#
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com.skyler.data: debug
  path: logs


feignClient:
  env:
    profile:
      skyler: feign.skyler.home

wechat:
  appId: ertetegfgdgdfgdfgfdg
  secret: dwtretgefghrththhfhfg
  acc_token_url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${wechat.appId}&secret=${wechat.secret}
  js_token_url: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=ACCESS_TOKEN&type=jsapi
  header_referer: referer